# LIMPIEZA DE DATOS Y UNIFICACION EN UN UNICO DATASET #

Incluir la columna distrito al datase base (general_data)

In [8]:
import pandas as pd
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ------------------------------------- 250.9/250.9 kB 15.0 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))': /packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
#Carga del datasets

general = pd.read_csv("general_data.csv")  
barrios  = pd.read_excel("Barrios.xlsx")

In [10]:
#Columnas necesarias
barrios_info = barrios[["NOMBRE", "NOMDIS"]].rename(columns={"NOMBRE":"Barrio","NOMDIS":"Distrito"})

In [11]:
# Columna de distrito incluida
general_distrito = general.merge(barrios_info, on="Barrio")

print(general_distrito.head())

             Barrio  anyo  Inversion  airbnb  Superficie (Ha.)  \
0          Abrantes  2020        0.0       3             156.0
1           Acacias  2020        0.0      44             107.0
2           Adelfas  2020        0.0      20              64.0
3        Aeropuerto  2020        0.0       0            2963.0
4  Alameda de Osuna  2020        0.0       9             197.0

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                         196.00                         8.43
1                         343.00                         6.42
2                         288.00                         8.20
3                           0.62                        12.07
4                          99.00                         5.80

   Población en etapas educativas  \
0                            5029
1                            3958
2                            2516
3                             292
4                            3256

   Tasa de crecimiento demográfico (porcentaje)  \
0                                          3.21
1                                          0.09
2                                          0.70
3                                          3.13
4                                          0.41

   Porcentaje de envejecimiento (Población mayor de 65 años/Población total)  \
0                                              17.95
1                                              22.68
2                                              21.28
3                                              15.07
4                                              25.63

   ...  Personas con nacionalidad española  \
0  ...                               24709
1  ...                               34207
2  ...                               17171
3  ...                                1474
4  ...                               18422

   Personas con nacionalidad extranjera  \
0                                  6030
1                                  2577
2                                  1303
3                                   377
4                                  1104

   Renta neta media anual de los hogares (Urban Audit)  \
0                                            28513.0
1                                            45516.0
2                                            46145.0
3                                            25366.0
4                                            52966.0

   num_hogar_monoparental  anyo_timestamp  poblacion_noEstudios  \
0                     311      2020-01-01                  5037
1                     290      2020-01-01                  2988
2                     179      2020-01-01                   349
3                      19      2020-01-01                   328
4                     241      2020-01-01                   896

   poblacion_estudios_medios  poblacion_estudios_superiores  precio_vivienda  \
0                      13210                           4237          1901.37
1                      11473                          12591          4646.78
2                       5752                           6292          4540.71
3                        892                            187             0.00
4                       1577                           7495          2961.24

      Distrito
0  Carabanchel
1   Arganzuela
2       Retiro
3      Barajas
4      Barajas

[5 rows x 29 columns]

In [12]:
general_distrito

,Barrio,anyo,Inversion,airbnb,Superficie (Ha.),Población densidad (hab./Ha.),Tasa bruta de natalidad (‰),Población en etapas educativas,Tasa de crecimiento demográfico (porcentaje),Porcentaje de envejecimiento (Población mayor de 65 años/Población total),...,Personas con nacionalidad española,Personas con nacionalidad extranjera,Renta neta media anual de los hogares (Urban Audit),num_hogar_monoparental,anyo_timestamp,poblacion_noEstudios,poblacion_estudios_medios,poblacion_estudios_superiores,precio_vivienda,Distrito
0,Abrantes,2020,0.00,3,156.00,196.000000,8.43,5029,3.21,17.95,...,24709,6030,28513.0,311,2020-01-01,5037,13210,4237,1901.37,Carabanchel
1,Acacias,2020,0.00,44,107.00,343.000000,6.42,3958,0.09,22.68,...,34207,2577,45516.0,290,2020-01-01,2988,11473,12591,4646.78,Arganzuela
2,Adelfas,2020,0.00,20,64.00,288.000000,8.20,2516,0.70,21.28,...,17171,1303,46145.0,179,2020-01-01,349,5752,6292,4540.71,Retiro
3,Aeropuerto,2020,0.00,0,2963.00,0.620000,12.07,292,3.13,15.07,...,1474,377,25366.0,19,2020-01-01,328,892,187,0.00,Barajas
4,Alameda de Osuna,2020,0.00,9,197.00,99.000000,5.80,3256,0.41,25.63,...,18422,1104,52966.0,241,2020-01-01,896,1577,7495,2961.24,Barajas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,Vinateros,2024,1009339.00,15,59.40,291.734007,6.63,1876,-1.71,27.89,...,14427,2458,0.0,143,2024-01-01,2303,7694,3915,2655.00,Moratalaz
636,Vista Alegre,2024,0.00,107,158.92,315.586459,6.52,5753,-2.66,21.82,...,34979,12748,0.0,324,2024-01-01,6798,24599,7678,2443.73,Carabanchel
637,Zofío,2024,7677044.86,36,77.40,197.648579,7.53,1870,-2.53,17.47,...,10208,4173,0.0,120,2024-01-01,2248,7463,875,2103.87,Usera
638,Águilas,2024,0.00,22,360.96,145.004987,5.44,5791,-0.71,27.53,...,44084,7183,0.0,427,2024-01-01,2624,22001,9043,2491.21,Latina
639,Ángeles,2024,0.00,29,193.53,190.115228,8.39,4397,-5.69,23.10,...,27211,7615,0.0,314,2024-01-01,5439,12883,5754,0.00,Villaverde

In [13]:
# Poner Distrito antes de Barrio
cols = general_distrito.columns.tolist()

# Mover Distrito a la posición 0
cols.insert(cols.index("Barrio"), cols.pop(cols.index("Distrito")))

# Reordenar dataframe
general_distrito = general_distrito[cols]

print(general_distrito.head())

      Distrito            Barrio  anyo  Inversion  airbnb  Superficie (Ha.)  \
0  Carabanchel          Abrantes  2020        0.0       3             156.0
1   Arganzuela           Acacias  2020        0.0      44             107.0
2       Retiro           Adelfas  2020        0.0      20              64.0
3      Barajas        Aeropuerto  2020        0.0       0            2963.0
4      Barajas  Alameda de Osuna  2020        0.0       9             197.0

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                         196.00                         8.43
1                         343.00                         6.42
2                         288.00                         8.20
3                           0.62                        12.07
4                          99.00                         5.80

   Población en etapas educativas  \
0                            5029
1                            3958
2                            2516
3                             292
4                            3256

   Tasa de crecimiento demográfico (porcentaje)  ...  Total hogares  \
0                                          3.21  ...          11036
1                                          0.09  ...          15442
2                                          0.70  ...           7613
3                                          3.13  ...            687
4                                          0.41  ...           7249

   Personas con nacionalidad española  Personas con nacionalidad extranjera  \
0                               24709                                  6030
1                               34207                                  2577
2                               17171                                  1303
3                                1474                                   377
4                               18422                                  1104

   Renta neta media anual de los hogares (Urban Audit)  \
0                                            28513.0
1                                            45516.0
2                                            46145.0
3                                            25366.0
4                                            52966.0

   num_hogar_monoparental  anyo_timestamp  poblacion_noEstudios  \
0                     311      2020-01-01                  5037
1                     290      2020-01-01                  2988
2                     179      2020-01-01                   349
3                      19      2020-01-01                   328
4                     241      2020-01-01                   896

   poblacion_estudios_medios  poblacion_estudios_superiores  precio_vivienda
0                      13210                           4237          1901.37
1                      11473                          12591          4646.78
2                       5752                           6292          4540.71
3                        892                            187             0.00
4                       1577                           7495          2961.24

[5 rows x 29 columns]

In [14]:
general_distrito.to_csv("general_con_distrito.csv", index=False)

In [15]:
general_distrito

,Distrito,Barrio,anyo,Inversion,airbnb,Superficie (Ha.),Población densidad (hab./Ha.),Tasa bruta de natalidad (‰),Población en etapas educativas,Tasa de crecimiento demográfico (porcentaje),...,Total hogares,Personas con nacionalidad española,Personas con nacionalidad extranjera,Renta neta media anual de los hogares (Urban Audit),num_hogar_monoparental,anyo_timestamp,poblacion_noEstudios,poblacion_estudios_medios,poblacion_estudios_superiores,precio_vivienda
0,Carabanchel,Abrantes,2020,0.00,3,156.00,196.000000,8.43,5029,3.21,...,11036,24709,6030,28513.0,311,2020-01-01,5037,13210,4237,1901.37
1,Arganzuela,Acacias,2020,0.00,44,107.00,343.000000,6.42,3958,0.09,...,15442,34207,2577,45516.0,290,2020-01-01,2988,11473,12591,4646.78
2,Retiro,Adelfas,2020,0.00,20,64.00,288.000000,8.20,2516,0.70,...,7613,17171,1303,46145.0,179,2020-01-01,349,5752,6292,4540.71
3,Barajas,Aeropuerto,2020,0.00,0,2963.00,0.620000,12.07,292,3.13,...,687,1474,377,25366.0,19,2020-01-01,328,892,187,0.00
4,Barajas,Alameda de Osuna,2020,0.00,9,197.00,99.000000,5.80,3256,0.41,...,7249,18422,1104,52966.0,241,2020-01-01,896,1577,7495,2961.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,Moratalaz,Vinateros,2024,1009339.00,15,59.40,291.734007,6.63,1876,-1.71,...,7244,14427,2458,0.0,143,2024-01-01,2303,7694,3915,2655.00
636,Carabanchel,Vista Alegre,2024,0.00,107,158.92,315.586459,6.52,5753,-2.66,...,17773,34979,12748,0.0,324,2024-01-01,6798,24599,7678,2443.73
637,Usera,Zofío,2024,7677044.86,36,77.40,197.648579,7.53,1870,-2.53,...,5107,10208,4173,0.0,120,2024-01-01,2248,7463,875,2103.87
638,Latina,Águilas,2024,0.00,22,360.96,145.004987,5.44,5791,-0.71,...,20965,44084,7183,0.0,427,2024-01-01,2624,22001,9043,2491.21
639,Villaverde,Ángeles,2024,0.00,29,193.53,190.115228,8.39,4397,-5.69,...,13423,27211,7615,0.0,314,2024-01-01,5439,12883,5754,0.00

Estandarizar columnas en general_con_distrito

In [41]:
import pandas as pd

general = pd.read_csv("general_con_distrito.csv")

In [42]:
general

,Distrito,Barrio,anyo,Inversion,airbnb,Superficie (Ha.),Población densidad (hab./Ha.),Tasa bruta de natalidad (‰),Población en etapas educativas,Tasa de crecimiento demográfico (porcentaje),...,Total hogares,Personas con nacionalidad española,Personas con nacionalidad extranjera,Renta neta media anual de los hogares (Urban Audit),num_hogar_monoparental,anyo_timestamp,poblacion_noEstudios,poblacion_estudios_medios,poblacion_estudios_superiores,precio_vivienda
0,Carabanchel,Abrantes,2020,0.00,3,156.00,196.000000,8.43,5029,3.21,...,11036,24709,6030,28513.0,311,2020-01-01,5037,13210,4237,1901.37
1,Arganzuela,Acacias,2020,0.00,44,107.00,343.000000,6.42,3958,0.09,...,15442,34207,2577,45516.0,290,2020-01-01,2988,11473,12591,4646.78
2,Retiro,Adelfas,2020,0.00,20,64.00,288.000000,8.20,2516,0.70,...,7613,17171,1303,46145.0,179,2020-01-01,349,5752,6292,4540.71
3,Barajas,Aeropuerto,2020,0.00,0,2963.00,0.620000,12.07,292,3.13,...,687,1474,377,25366.0,19,2020-01-01,328,892,187,0.00
4,Barajas,Alameda de Osuna,2020,0.00,9,197.00,99.000000,5.80,3256,0.41,...,7249,18422,1104,52966.0,241,2020-01-01,896,1577,7495,2961.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,Moratalaz,Vinateros,2024,1009339.00,15,59.40,291.734007,6.63,1876,-1.71,...,7244,14427,2458,0.0,143,2024-01-01,2303,7694,3915,2655.00
636,Carabanchel,Vista Alegre,2024,0.00,107,158.92,315.586459,6.52,5753,-2.66,...,17773,34979,12748,0.0,324,2024-01-01,6798,24599,7678,2443.73
637,Usera,Zofío,2024,7677044.86,36,77.40,197.648579,7.53,1870,-2.53,...,5107,10208,4173,0.0,120,2024-01-01,2248,7463,875,2103.87
638,Latina,Águilas,2024,0.00,22,360.96,145.004987,5.44,5791,-0.71,...,20965,44084,7183,0.0,427,2024-01-01,2624,22001,9043,2491.21
639,Villaverde,Ángeles,2024,0.00,29,193.53,190.115228,8.39,4397,-5.69,...,13423,27211,7615,0.0,314,2024-01-01,5439,12883,5754,0.00

In [ ]:
import pandas as pd
import unicodedata, re

#Cargar CSV
df = pd.read_csv("general_con_distrito.csv", encoding="utf-8")

# Normalizar encabezados
df.columns = [re.sub(r"\s+", " ", c).strip() for c in df.columns]

# Renombrar a 'Distrito'
for c in df.columns:
    if c.lower().strip() == "distrito":
        df = df.rename(columns={c: "Distrito"})

# Función de estandarización
def normaliza_valor_distrito(x: str) -> str:
    if pd.isna(x):
        return x
    s = str(x)
    # quitar numeración tipo "01. Centro"
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)
    # quitar tildes
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))
    # dejar solo letras (incluye Ñ)
    s = re.sub(r"[^A-Za-zÑñ]", "", s)
    # mayúsculas
    return s.upper()

# Crear columna estandarizada
df["Distrito"] = df["Distrito"].apply(normaliza_valor_distrito)

df.to_csv("general_con_distrito_std.csv", index=False, encoding="utf-8-sig")
print("Archivo limpio guardado como general_con_distrito_std.csv")

Archivo limpio guardado como general_con_distrito_std.csv

Estandarizar columnas en alquiler_venta_procesado

In [ ]:
import pandas as pd
import unicodedata
import re

# Cargar CSV
try:
    df = pd.read_csv("venta_alquiler_procesado.csv", encoding="utf-8")
except UnicodeDecodeError:
    df = pd.read_csv("venta_alquiler_procesado.csv", encoding="cp1252")

# Normalizar encabezados
df.columns = [re.sub(r"\s+", " ", c).strip() for c in df.columns]

# Asegurar nombre 'Distrito'
for c in df.columns:
    if c.lower().strip() == "distrito" and c != "Distrito":
        df = df.rename(columns={c: "Distrito"})
        break

if "Distrito" not in df.columns:
    raise KeyError("No se encontró una columna llamada 'Distrito' (o equivalente).")

# Estandarización de valores de Distrito
def normaliza_distrito(x: str) -> str:
    if pd.isna(x):
        return x
    s = str(x)
    # Quitar prefijo de numeración tipo "01. Centro"
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)
    # Quitar tildes
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))
    # Dejar solo letras (incluye Ñ/ñ); elimina números, espacios y símbolos
    s = re.sub(r"[^A-Za-zÑñ]", "", s)
    # Mayúsculas
    return s.upper()

# Aplicar estandarización
df["Distrito"] = df["Distrito"].apply(normaliza_distrito)

# Unificar nombre de año 
df = df.rename(columns={"Año": "anyo", "año": "anyo"})

df.to_csv("venta_alquiler_procesado_std.csv", index=False, encoding="utf-8-sig")

print("Ejemplos de Distrito estandarizado:", df["Distrito"].dropna().unique()[:10])

✅ Archivo guardado: venta_alquiler_procesado_std.csv
Ejemplos de Distrito estandarizado: ['CENTRO' 'ARGANZUELA' 'RETIRO' 'SALAMANCA' 'CHAMARTIN' 'TETUAN'
 'CHAMBERI' 'FUENCARRALELPARDO' 'MONCLOAARAVACA' 'LATINA']

## Unificacion de dataset general_con_distrito_std con venta_alquiler_procesado_std ##

In [ ]:
import pandas as pd

# Cargar datasets ya estandarizados
general = pd.read_csv("general_con_distrito_std.csv", encoding="utf-8")
precios = pd.read_csv("venta_alquiler_procesado_std.csv", encoding="utf-8")

# Renombrar columnas de año 
general = general.rename(columns={"Año":"anyo", "año":"anyo"})
precios = precios.rename(columns={"Año":"anyo", "año":"anyo"})

# Replicar por cada barrio de su distrito
mapa_barrios = general[["Distrito","Barrio"]].drop_duplicates()
precios_expandido = precios.merge(mapa_barrios, on="Distrito", how="left")

base_2020_2024 = general.merge(
    precios_expandido[["anyo","Distrito","Barrio","Precio_venta","Precio_alquiler"]],
    on=["anyo","Distrito","Barrio"], how="left"
)

precios_2011_2019 = (
    precios_expandido.loc[precios_expandido["anyo"] < 2020,
                          ["anyo","Distrito","Barrio","Precio_venta","Precio_alquiler"]]
    .copy()
)

# Agregar las columnas de general como vacías
faltan_cols = [c for c in base_2020_2024.columns if c not in precios_2011_2019.columns]
for c in faltan_cols:
    precios_2011_2019[c] = pd.NA

# Reordenar columnas
precios_2011_2019 = precios_2011_2019[base_2020_2024.columns]

# Concatenar ambos bloques
dataset_final = pd.concat([precios_2011_2019, base_2020_2024], ignore_index=True)

dataset_final.to_csv("dataset_general_2011_2024.csv", index=False, encoding="utf-8-sig")

print("Años incluidos:", dataset_final["anyo"].min(), "-", dataset_final["anyo"].max())
print("Filas totales:", len(dataset_final))
print("Ejemplo:\n", dataset_final.head())

C:\Users\andre\AppData\Local\Temp\ipykernel_22300\2845372774.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataset_final = pd.concat([precios_2011_2019, base_2020_2024], ignore_index=True)

Años incluidos: 2011 - 2024
Filas totales: 21248
Ejemplo:
   Distrito       Barrio  anyo  Inversion airbnb  Superficie (Ha.)  \
0   CENTRO       Cortes  2011        NaN   <NA>               NaN
1   CENTRO  Embajadores  2011        NaN   <NA>               NaN
2   CENTRO     Justicia  2011        NaN   <NA>               NaN
3   CENTRO      Palacio  2011        NaN   <NA>               NaN
4   CENTRO          Sol  2011        NaN   <NA>               NaN

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

  Población en etapas educativas  \
0                           <NA>
1                           <NA>
2                           <NA>
3                           <NA>
4                           <NA>

   Tasa de crecimiento demográfico (porcentaje)  ...  \
0                                           NaN  ...
1                                           NaN  ...
2                                           NaN  ...
3                                           NaN  ...
4                                           NaN  ...

   Personas con nacionalidad extranjera  \
0                                  <NA>
1                                  <NA>
2                                  <NA>
3                                  <NA>
4                                  <NA>

  Renta neta media anual de los hogares (Urban Audit)  num_hogar_monoparental  \
0                                                NaN                     <NA>
1                                                NaN                     <NA>
2                                                NaN                     <NA>
3                                                NaN                     <NA>
4                                                NaN                     <NA>

   anyo_timestamp poblacion_noEstudios poblacion_estudios_medios  \
0             NaN                 <NA>                      <NA>
1             NaN                 <NA>                      <NA>
2             NaN                 <NA>                      <NA>
3             NaN                 <NA>                      <NA>
4             NaN                 <NA>                      <NA>

   poblacion_estudios_superiores precio_vivienda Precio_venta Precio_alquiler
0                           <NA>             NaN       3989.0            15.3
1                           <NA>             NaN       3989.0            15.3
2                           <NA>             NaN       3989.0            15.3
3                           <NA>             NaN       3989.0            15.3
4                           <NA>             NaN       3989.0            15.3

[5 rows x 31 columns]

## Unificar con dataset de esperanza de vida ##

In [ ]:
import pandas as pd
import unicodedata, re

# Normalizar nombres de distrito
def norm_distrito(s):
    if pd.isna(s):
        return s
    s = str(s)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)  # quitar numeración tipo "01. "
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))
    s = re.sub(r"[^A-Za-zÑñ]", "", s)  # solo letras
    return s.upper()

general = pd.read_csv("dataset_general_2011_2024.csv", encoding="utf-8")
ev = pd.read_csv("esperanza_vida.csv", sep=";", encoding="utf-8-sig")

# Normalizar columnas de esperanza de vida, renombrando la columna año
ev = ev.rename(columns={"Año":"anyo", "año":"anyo"})

# Limpiar columna Distrito
ev["Distrito"] = ev["Distrito"].map(norm_distrito)

# Convertir a numérico la esperanza de vida
ev["esperanza_vida"] = ev["Esperanza de vida"].astype(str).str.replace(",", ".")
ev["esperanza_vida"] = pd.to_numeric(ev["esperanza_vida"], errors="coerce")

# MFiltrar columnas necesarias
ev = ev[["anyo","Distrito","esperanza_vida"]]

# Normalizar distritos en la base general 
general["Distrito"] = general["Distrito"].map(norm_distrito)

# Unir datasets (anyo + Distrito)
merged = general.merge(ev, on=["anyo","Distrito"], how="left")

merged.to_csv("dataset_general_2011_2024_ev.csv", index=False, encoding="utf-8-sig")

print("Dataset unificado guardado en dataset_general_2011_2024_ev.csv")
print("Columnas:", merged.columns.tolist()[:10], "...")
print("Ejemplo:\n", merged.head())

✅ Dataset unificado guardado en dataset_general_2011_2024_ev.csv
Columnas: ['Distrito', 'Barrio', 'anyo', 'Inversion', 'airbnb', 'Superficie (Ha.)', 'Población densidad (hab./Ha.)', 'Tasa bruta de natalidad (‰)', 'Población en etapas educativas', 'Tasa de crecimiento demográfico (porcentaje)'] ...
Ejemplo:
   Distrito       Barrio  anyo  Inversion  airbnb  Superficie (Ha.)  \
0   CENTRO       Cortes  2011        NaN     NaN               NaN
1   CENTRO  Embajadores  2011        NaN     NaN               NaN
2   CENTRO     Justicia  2011        NaN     NaN               NaN
3   CENTRO      Palacio  2011        NaN     NaN               NaN
4   CENTRO          Sol  2011        NaN     NaN               NaN

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

   Población en etapas educativas  \
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN

   Tasa de crecimiento demográfico (porcentaje)  ...  \
0                                           NaN  ...
1                                           NaN  ...
2                                           NaN  ...
3                                           NaN  ...
4                                           NaN  ...

   Renta neta media anual de los hogares (Urban Audit)  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   num_hogar_monoparental  anyo_timestamp  poblacion_noEstudios  \
0                     NaN             NaN                   NaN
1                     NaN             NaN                   NaN
2                     NaN             NaN                   NaN
3                     NaN             NaN                   NaN
4                     NaN             NaN                   NaN

   poblacion_estudios_medios  poblacion_estudios_superiores  precio_vivienda  \
0                        NaN                            NaN              NaN
1                        NaN                            NaN              NaN
2                        NaN                            NaN              NaN
3                        NaN                            NaN              NaN
4                        NaN                            NaN              NaN

   Precio_venta  Precio_alquiler  esperanza_vida
0        3989.0             15.3            83.2
1        3989.0             15.3            83.2
2        3989.0             15.3            83.2
3        3989.0             15.3            83.2
4        3989.0             15.3            83.2

[5 rows x 32 columns]

Estandarización del dataset de renta_media_persona

In [ ]:
import pandas as pd
import unicodedata, re

# Cargar  del archivo con tolerancia de encoding y separador ;
try:
    df = pd.read_csv("renta_media.csv", sep=";", encoding="utf-8-sig")
except UnicodeDecodeError:
    df = pd.read_csv("renta_media.csv", sep=";", encoding="cp1252")

# Limpiar encabezados quitando ';', espacios raros
df.columns = [c.strip().replace(";", "") for c in df.columns]

# Unificar columna año
for cand in ("Año", "año", "Ano", "ano"):
    if cand in df.columns:
        df = df.rename(columns={cand: "anyo"})
        break

# Unificar columna 'Distrito'
for c in df.columns:
    if c.lower().strip() == "distrito" and c != "Distrito":
        df = df.rename(columns={c: "Distrito"})
        break
if "Distrito" not in df.columns:
    raise KeyError("No se encontró la columna 'Distrito'.")

# Normalizar valores de Distrito: sin números, sin espacios/símbolos, sin tildes, ni mayúsculas 
def normaliza_distrito(x: str) -> str:
    if pd.isna(x): return x
    s = str(x)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)  # quita prefijo tipo '01. '
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))  # sin tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)       # solo letras (quita espacios, guiones, números, etc.)
    return s.upper()

df["Distrito"] = df["Distrito"].map(normaliza_distrito)

df.to_csv("renta_media_procesado_std.csv", index=False, encoding="utf-8-sig")
print("Guardado renta_media_procesado_std.csv")
print(df[["anyo","Distrito"]].head())

✅ Guardado renta_media_procesado_std.csv
   anyo    Distrito
0  2015      CENTRO
1  2015  ARGANZUELA
2  2015      RETIRO
3  2015   SALAMANCA
4  2015   CHAMARTIN

## Unificación del dataset renta_media_persona con el dataset_general_2011_2024_ev ##

In [ ]:
import pandas as pd
import unicodedata, re

# Normalizar columna 'Distrito' 
def norm_distrito(s):
    if pd.isna(s): return s
    s = str(s)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)                     # quita "01. "
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(ch))               # sin tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)                           # solo letras
    return s.upper()

base = pd.read_csv("dataset_general_2011_2024_ev.csv", encoding="utf-8")
renta = pd.read_csv("renta_media_procesado_std.csv", encoding="utf-8-sig")

# Unificar columna 'Año'
base = base.rename(columns={"Año":"anyo", "año":"anyo"})
renta = renta.rename(columns={"Año":"anyo", "año":"anyo"})

# normalizar distritos en ambos 
base["Distrito"]  = base["Distrito"].map(norm_distrito)
renta["Distrito"] = renta["Distrito"].map(norm_distrito)

# Convertir a numérico la columna renta
col_renta = next((c for c in renta.columns if "renta" in c.lower() and c not in ["anyo","Distrito"]), None)
if col_renta is None:
    # si no tiene "renta" en el nombre, toma cualquier columna distinta a claves
    col_renta = [c for c in renta.columns if c not in ["anyo","Distrito"]][0]

# limpiar formato de símbolos y pasar a float
renta_val = (renta[col_renta].astype(str)
             .str.replace(r"[^0-9\-,\.]", "", regex=True)
             .str.replace(".", "", regex=False)
             .str.replace(",", ".", regex=False))
renta["renta_media_persona"] = pd.to_numeric(renta_val, errors="coerce")

renta_std = renta[["anyo","Distrito","renta_media_persona"]].copy()

# Unir por anyo + Distrito
merged = base.merge(renta_std, on=["anyo","Distrito"], how="left")

merged.to_csv("general_11_24_ev_renta.csv", index=False, encoding="utf-8-sig")

print("Guardado: general_11_24_ev_renta.csv")
print("Filas:", len(merged))
print("Años:", merged["anyo"].min(), "-", merged["anyo"].max())
print("Rentas faltantes tras el merge:", merged["renta_media_persona"].isna().sum())
print(merged[["anyo","Distrito","Barrio","renta_media_persona"]].head())

✅ Guardado: general_11_24_ev_renta.csv
Filas: 21248
Años: 2011 - 2024
Rentas faltantes tras el merge: 8960
   anyo Distrito       Barrio  renta_media_persona
0  2011   CENTRO       Cortes                  NaN
1  2011   CENTRO  Embajadores                  NaN
2  2011   CENTRO     Justicia                  NaN
3  2011   CENTRO      Palacio                  NaN
4  2011   CENTRO          Sol                  NaN

Estandarización y procesado de datos de datos demograficos INE

In [ ]:
import pandas as pd
import unicodedata, re

# Función para leer CSV aunque tengan distinto separador o codificación
def leer_csv_flexible(path):
    try:
        return pd.read_csv(path, engine="python", sep=None, encoding="utf-8-sig")
    except Exception:
        for enc in ["utf-8-sig", "utf-8", "cp1252"]:
            for sep in [";", ",", "\t", "|"]:
                try:
                    return pd.read_csv(path, sep=sep, encoding=enc)
                except Exception:
                    pass
    raise RuntimeError(f"No pude leer {path} con separadores/codificaciones comunes")

df = leer_csv_flexible("datos_demograficos_ine_procesado.csv")

# limpiar encabezados
df.columns = [c.replace(";", "").strip() for c in df.columns]

# unificar la columna 'Año' por anyo
for cand in ("Año", "año", "Ano", "ano", "year"):
    if cand in df.columns:
        df = df.rename(columns={cand: "anyo"})
        break

# Renombrar columna Distrito
cand_distrito = [c for c in df.columns if c.lower().strip() == "distrito"]
if cand_distrito:
    if cand_distrito[0] != "Distrito":
        df = df.rename(columns={cand_distrito[0]: "Distrito"})
else:
    raise KeyError(f"No se encontró la columna 'Distrito'. Columnas: {df.columns.tolist()}")

# Normalizar valores de la columna 'Distrito'
def normaliza_distrito(x):
    if pd.isna(x): return x
    s = str(x)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)                         # quita prefijo tipo '01. '
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(ch))                   # sin tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)                               # solo letras (sin espacios, números, guiones…)
    return s.upper()

df["Distrito"] = df["Distrito"].map(normaliza_distrito)

# normalizar 'anyo' a numérico
if "anyo" in df.columns:
    df["anyo"] = pd.to_numeric(df["anyo"], errors="coerce").astype("Int64")

df.to_csv("datos_demograficos_ine_std.csv", index=False, encoding="utf-8-sig")
print("Guardado: datos_demograficos_ine_std.csv")
print(df[["anyo","Distrito"]].head())

✅ Guardado: datos_demograficos_ine_std.csv
   anyo Distrito
0  2015   CENTRO
1  2016   CENTRO
2  2017   CENTRO
3  2018   CENTRO
4  2019   CENTRO

## Unificar con dataset general_11_24_ev_renta ##

In [ ]:
import pandas as pd
import unicodedata, re

general = pd.read_csv("general_11_24_ev_renta.csv", encoding="utf-8-sig")
demog   = pd.read_csv("datos_demograficos_ine_std.csv", encoding="utf-8-sig")

# Asegurar columnas claves
general = general.rename(columns={"Año": "anyo", "año": "anyo"})
demog   = demog.rename(columns={"Año": "anyo", "año": "anyo"})

# Normalizar valores de distrito 
def norm_distrito(s):
    if pd.isna(s): return s
    s = str(s)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)  # quitar numeración "01. "
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(ch))  # quitar tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)       # solo letras
    return s.upper()

general["Distrito"] = general["Distrito"].map(norm_distrito)
demog["Distrito"]   = demog["Distrito"].map(norm_distrito)

# Merge por anyo + Distrito
merged = general.merge(demog, on=["anyo","Distrito"], how="left")

merged.to_csv("general_11_24_ev_renta_demog.csv", index=False, encoding="utf-8-sig")

print("Guardado: general_11_24_ev_renta_demog.csv")
print("Filas:", len(merged))
print("Columnas:", len(merged.columns))
print(merged.head())

✅ Guardado: general_11_24_ev_renta_demog.csv
Filas: 21248
Columnas: 39
  Distrito       Barrio  anyo  Inversion  airbnb  Superficie (Ha.)  \
0   CENTRO       Cortes  2011        NaN     NaN               NaN
1   CENTRO  Embajadores  2011        NaN     NaN               NaN
2   CENTRO     Justicia  2011        NaN     NaN               NaN
3   CENTRO      Palacio  2011        NaN     NaN               NaN
4   CENTRO          Sol  2011        NaN     NaN               NaN

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

   Población en etapas educativas  \
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN

   Tasa de crecimiento demográfico (porcentaje)  ...  Precio_venta  \
0                                           NaN  ...        3989.0
1                                           NaN  ...        3989.0
2                                           NaN  ...        3989.0
3                                           NaN  ...        3989.0
4                                           NaN  ...        3989.0

   Precio_alquiler  esperanza_vida  renta_media_persona  Unnamed: 0  \
0             15.3            83.2                  NaN         NaN
1             15.3            83.2                  NaN         NaN
2             15.3            83.2                  NaN         NaN
3             15.3            83.2                  NaN         NaN
4             15.3            83.2                  NaN         NaN

   Edad media de la población_y  Población  \
0                           NaN        NaN
1                           NaN        NaN
2                           NaN        NaN
3                           NaN        NaN
4                           NaN        NaN

   Porcentaje de población de 65 y más años  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

   Porcentaje de población menor de 18 años  Tamaño medio del hogar_y
0                                       NaN                       NaN
1                                       NaN                       NaN
2                                       NaN                       NaN
3                                       NaN                       NaN
4                                       NaN                       NaN

[5 rows x 39 columns]

Estandarizacion del dataset paro_registrado_2012_2024_total

In [ ]:
import pandas as pd
import unicodedata, re

# Cargar CSV
try:
    df = pd.read_csv("paro_registrado_2012_2024_total.csv", sep=";", encoding="utf-8-sig")
except UnicodeDecodeError:
    df = pd.read_csv("paro_registrado_2012_2024_total.csv", sep=";", encoding="cp1252")

# Limpiar encabezados
df.columns = [c.replace(";", "").strip() for c in df.columns]

# Unificar columna año -> anyo
for cand in ("Año", "año", "Ano", "ano"):
    if cand in df.columns:
        df = df.rename(columns={cand: "anyo"})
        break

# Asegurar columna Distrito
for c in df.columns:
    if c.lower().strip() == "distrito" and c != "Distrito":
        df = df.rename(columns={c: "Distrito"})
        break
if "Distrito" not in df.columns:
    raise KeyError(f"No se encontró columna 'Distrito'. Columnas: {df.columns.tolist()}")

# Normalizar valores de Distrito
def normaliza_distrito(x: str) -> str:
    if pd.isna(x): return x
    s = str(x)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)  # quita prefijos "01. "
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))  # sin tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)       # solo letras (quita espacios, guiones, números…)
    return s.upper()

df["Distrito"] = df["Distrito"].map(normaliza_distrito)

# Normalizar año a numérico
if "anyo" in df.columns:
    df["anyo"] = pd.to_numeric(df["anyo"], errors="coerce").astype("Int64")

df.to_csv("paro_registrado_2012_2024_std.csv", index=False, encoding="utf-8-sig")

print("Guardado: paro_registrado_2012_2024_std.csv")
print(df[["anyo","Distrito"]].head())

✅ Guardado: paro_registrado_2012_2024_std.csv
   anyo    Distrito
0  2012      CENTRO
1  2012  ARGANZUELA
2  2012      RETIRO
3  2012   SALAMANCA
4  2012   CHAMARTIN

Cálculo de promedio anual de paro registrado

In [ ]:
import pandas as pd
import re

# Carga de CSV
paro = pd.read_csv("paro_registrado_2012_2024_std.csv", encoding="utf-8-sig")

# Asegurar nombres clave
paro = paro.rename(columns={"Año":"anyo", "año":"anyo", "Mes":"mes", "mes":"mes"})
paro_cols = [c for c in paro.columns if "paro" in c.lower() and c not in ["anyo","Distrito","mes"]]
if not paro_cols:
    raise KeyError(f"No se encontró columna de paro. Columnas disponibles: {paro.columns.tolist()}")

col_paro = paro_cols[0]

# Convertir la columna a numérico
def to_float_eu(series: pd.Series) -> pd.Series:
    s = series.astype(str)
    s = s.str.replace(r"[^0-9\-,\.]", "", regex=True)  # quitar símbolos extra
    s = s.str.replace(".", "", regex=False)            # quitar separador de miles
    s = s.str.replace(",", ".", regex=False)           # coma decimal → punto
    return pd.to_numeric(s, errors="coerce")

paro[col_paro] = to_float_eu(paro[col_paro])

# Calcular promedio anual
paro_anual = (
    paro.groupby(["anyo","Distrito"], as_index=False)[col_paro]
        .mean(numeric_only=True)
        .rename(columns={col_paro: "paro_registrado_anual"})
)

paro_anual.to_csv("paro_registrado_anual.csv", index=False, encoding="utf-8-sig")

print("Archivo guardado como paro_registrado_anual.csv")
print(paro_anual.info())
print(paro_anual.head())

✅ Archivo guardado como paro_registrado_anual.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anyo                   275 non-null    int64
 1   Distrito               275 non-null    object
 2   paro_registrado_anual  275 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.6+ KB
None
   anyo     Distrito  paro_registrado_anual
0  2012   ARGANZUELA           10850.166667
1  2012      BARAJAS            2642.166667
2  2012  CARABANCHEL           22368.250000
3  2012       CENTRO           11681.500000
4  2012    CHAMARTIN            6820.333333

## Unificacion con dataset paro_registrado_anual con el dataset general_11_24_ev_renta_demog ##

In [ ]:
import pandas as pd
import unicodedata, re

# Leer datsets
general = pd.read_csv("general_11_24_ev_renta_demog.csv", encoding="utf-8-sig")
paro    = pd.read_csv("paro_registrado_anual.csv", encoding="utf-8-sig")

# Asegurar columna anyo
general = general.rename(columns={"Año":"anyo", "año":"anyo"})
paro    = paro.rename(columns={"Año":"anyo", "año":"anyo"})

# Normalizar columna 'Distrito'
def norm_distrito(s):
    if pd.isna(s): return s
    s = str(s)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)                           # quitar numeración tipo 01.
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(ch))                     # quitar tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)                                 # solo letras
    return s.upper()

general["Distrito"] = general["Distrito"].map(norm_distrito)
paro["Distrito"]    = paro["Distrito"].map(norm_distrito)

# Merge por anyo + Distrito
merged = general.merge(paro, on=["anyo","Distrito"], how="left")

merged.to_csv("general_11_24_ev_renta_demog_paro.csv", index=False, encoding="utf-8-sig")

print("Guardado: general_11_24_ev_renta_demog_paro.csv")
print("Columnas totales:", len(merged.columns))
print("Ejemplo:\n", merged[["anyo","Distrito","paro_registrado_anual"]].head())

✅ Guardado: general_11_24_ev_renta_demog_paro.csv
Columnas totales: 40
Ejemplo:
    anyo Distrito  paro_registrado_anual
0  2011   CENTRO                    NaN
1  2011   CENTRO                    NaN
2  2011   CENTRO                    NaN
3  2011   CENTRO                    NaN
4  2011   CENTRO                    NaN

Estandarización de columnas de poblacion del dataset poblacion_2011_2022_std

In [ ]:
import pandas as pd

pobl = pd.read_csv("poblacion_2011_2022_std.csv", encoding="utf-8-sig")

col = "poblacion_anual"

# limpiar y convertir a float
pobl[col] = (pobl[col].astype(str)
             .str.replace(r"[^0-9\-\.,]", "", regex=True)  # quita símbolos
             .str.replace(".", "", regex=False)            # miles
             .str.replace(",", ".", regex=False))          # coma->punto
pobl[col] = pd.to_numeric(pobl[col], errors="coerce")

# Pasar a entero
pobl[col] = pobl[col].round(0).astype("Int64")

pobl.to_csv("poblacion_2011_2022_std.csv", index=False, encoding="utf-8-sig")

print("Actualizado sin decimales en poblacion_anual")
print(pobl.dtypes)
print(pobl.head())

✅ Actualizado sin decimales en poblacion_anual
anyo                int64
Distrito           object
poblacion_anual     Int64
dtype: object
   anyo     Distrito  poblacion_anual
0  2011   ARGANZUELA         15441730
1  2011      BARAJAS          4623610
2  2011  CARABANCHEL         25263540
3  2011       CENTRO         14089030
4  2011    CHAMARTIN         14578910

## Unificacion con el dataset poblacion_2011_2022_std con general_11_24_ev_renta_demog_paro ##

In [ ]:
import pandas as pd
import re, unicodedata

# helper para normalizar distrito 
def norm_distrito(s):
    if pd.isna(s): return s
    s = str(s)
    s = re.sub(r"^\s*\d{1,2}\.\s*", "", s)                     # quita "01. "
    s = "".join(ch for ch in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(ch))               # sin tildes
    s = re.sub(r"[^A-Za-zÑñ]", "", s)                           # solo letras
    return s.upper()

# Cargar CSV
base = pd.read_csv("general_11_24_ev_renta_demog_paro.csv", encoding="utf-8-sig")
pobl = pd.read_csv("poblacion_2011_2022_std.csv", encoding="utf-8-sig")

# Asegurar nombres clave y formato coherente
base = base.rename(columns={"Año":"anyo", "año":"anyo"})
pobl = pobl.rename(columns={"Año":"anyo", "año":"anyo"})

base["Distrito"] = base["Distrito"].map(norm_distrito)
pobl["Distrito"] = pobl["Distrito"].map(norm_distrito)

# Asegurar que el nombre de la columna 'poblacion_anual' 
if "poblacion_anual" not in pobl.columns:
    cand = next(c for c in pobl.columns if "pobl" in c.lower() or "total" in c.lower())
    pobl = pobl.rename(columns={cand: "poblacion_anual"})

# Asegurar que sea numérica
pobl["poblacion_anual"] = pd.to_numeric(pobl["poblacion_anual"], errors="coerce")

# si hay duplicados los consolidamos con media
pobl = (pobl.groupby(["anyo","Distrito"], as_index=False)["poblacion_anual"]
            .mean(numeric_only=True))

# Merge
merged = base.merge(pobl, on=["anyo","Distrito"], how="left")

merged.to_csv("general_11_24_ev_renta_demog_paro_pobl.csv", index=False, encoding="utf-8-sig")

print("Guardado: general_11_24_ev_renta_demog_paro_pobl.csv")
print("Filas:", len(merged), "| Columnas:", len(merged.columns))
print("Años:", merged["anyo"].min(), "-", merged["anyo"].max())
print("Faltantes en poblacion_anual:", merged["poblacion_anual"].isna().sum())
print(merged[["anyo","Distrito","poblacion_anual"]].head())

✅ Guardado: general_11_24_ev_renta_demog_paro_pobl.csv
Filas: 21248 | Columnas: 41
Años: 2011 - 2024
Faltantes en poblacion_anual: 3072
   anyo Distrito  poblacion_anual
0  2011   CENTRO       14089030.0
1  2011   CENTRO       14089030.0
2  2011   CENTRO       14089030.0
3  2011   CENTRO       14089030.0
4  2011   CENTRO       14089030.0

In [ ]:
general_11_24_ev_renta_demog_paro_pobl = pd.read_csv("general_11_24_ev_renta_demog_paro_pobl.csv")

In [ ]:
general_11_24_ev_renta_demog_paro_pobl

,Distrito,Barrio,anyo,Inversion,airbnb,Superficie (Ha.),Población densidad (hab./Ha.),Tasa bruta de natalidad (‰),Población en etapas educativas,Tasa de crecimiento demográfico (porcentaje),...,esperanza_vida,renta_media_persona,Unnamed: 0,Edad media de la población_y,Población,Porcentaje de población de 65 y más años,Porcentaje de población menor de 18 años,Tamaño medio del hogar_y,paro_registrado_anual,poblacion_anual
0,CENTRO,Cortes,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14089030.0
1,CENTRO,Embajadores,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14089030.0
2,CENTRO,Justicia,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14089030.0
3,CENTRO,Palacio,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14089030.0
4,CENTRO,Sol,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14089030.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21243,VILLAVERDE,Ángeles,2024,0.0,29.0,193.53,190.115228,8.39,4397.0,-5.69,...,88.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9369.666667,NaN
21244,VILLAVERDE,Ángeles,2024,0.0,29.0,193.53,190.115228,8.39,4397.0,-5.69,...,88.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9369.666667,NaN
21245,VILLAVERDE,Ángeles,2024,0.0,29.0,193.53,190.115228,8.39,4397.0,-5.69,...,88.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9369.666667,NaN
21246,VILLAVERDE,Ángeles,2024,0.0,29.0,193.53,190.115228,8.39,4397.0,-5.69,...,88.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9369.666667,NaN
21247,VILLAVERDE,Ángeles,2024,0.0,29.0,193.53,190.115228,8.39,4397.0,-5.69,...,88.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9369.666667,NaN

## Unificar dataset SuperficieZonasVerdesDistritosCalles_std con dataset general_11_24_ev_renta_demog_paro_pobl ##

In [ ]:
import pandas as pd

# Cargar CSV (con ;)
try:
    zv = pd.read_csv("SuperficieZonasVerdesDistritosCalles_std.csv", sep=";", encoding="utf-8-sig")
except UnicodeDecodeError:
    zv = pd.read_csv("SuperficieZonasVerdesDistritosCalles_std.csv", sep=";", encoding="cp1252")

# limpiar encabezados
zv.columns = [c.replace("\ufeff","").strip() for c in zv.columns]

# asegurar claves estándar
for cand in ("Año","año","Ano","ano"):
    if cand in zv.columns: 
        zv = zv.rename(columns={cand:"anyo"})
        break

# Asegurar que la columna 'Distrito' se llame así
for c in list(zv.columns):
    if c.lower().strip() == "distrito" and c != "Distrito":
        zv = zv.rename(columns={c:"Distrito"})
        break

print("ZV cols:", zv.columns.tolist())  # Asegurar que la columna 'Distrito' y 'anyo' se llamen así

# Cargar CSV
general = pd.read_csv("general_11_24_ev_renta_demog_paro_pobl.csv", encoding="utf-8-sig")
general.columns = [c.replace("\ufeff","").strip() for c in general.columns]
general = general.rename(columns={"Año":"anyo", "año":"anyo"})

# Merge anyo + Distrito
merged = general.merge(zv, on=["anyo","Distrito"], how="left")

merged.to_csv("general_11_24_ev_renta_demog_paro_pobl_zv.csv", index=False, encoding="utf-8-sig")
print("Unificado y guardado en general_11_24_ev_renta_demog_paro_pobl_zv.csv")

ZV cols: ['Distrito', 'ha de ZONAS VERDES Y PARQUES en distrito', 'anyo']
✅ Unificado y guardado en general_11_24_ev_renta_demog_paro_pobl_zv.csv

Correción y estandarización de columnas del datset de inversión

In [ ]:
import pandas as pd
import unicodedata, re

# Funciones auxiliares para limpiar y estandarizar texto
# slug(s):   convierte un string en un identificador simple (solo letras minúsculas y guiones)
# normalize_col(c): prepara nombres de columnas (sin acentos, minúsculas, con guiones bajos)
def slug(s: str) -> str:
    s = unicodedata.normalize("NFKD", str(s))
    s = "".join(c for c in s if not unicodedata.combining(c)).lower().strip()
    s = re.sub(r"[\s\-]+", "_", s)
    s = re.sub(r"[^a-z0-9_]+", "", s)
    return s

def normalize_col(c: str) -> str:
    s = unicodedata.normalize("NFKD", str(c))
    s = "".join(ch for ch in s if not unicodedata.combining(ch)).lower().strip()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s

# Cargar .xlsx
df = pd.read_excel("inversiones_obra.xlsx", sheet_name=0)
df.columns = [normalize_col(c) for c in df.columns]

# estandarizar la columna 'Distrito'
df["distrito_std"] = df["distrito"].map(slug)

# construir base SIN duplicar 'distrito'
base = df.loc[:, ["distrito_std", "ano_inicio", "codigo_pep", "ano_de_finalizacion"]].copy()
base = base.rename(columns={
    "distrito_std": "distrito",  # ya estandarizado (minúsculas, sin acentos ni espacios)
    "ano_inicio": "anyo",        # renombramos columna
    "codigo_pep": "codigo"
})

base["anyo"] = pd.to_numeric(base["anyo"], errors="coerce").astype("Int64")
base["ano_de_finalizacion"] = pd.to_numeric(base["ano_de_finalizacion"], errors="coerce").astype("Int64")

# Conteos por AÑO DE INICIO 
iniciadas = (
    base.groupby(["distrito", "anyo"], as_index=False)["codigo"]
        .nunique()
        .rename(columns={"codigo": "obras_iniciadas"})
)

finalizadas = (
    base[base["ano_de_finalizacion"].notna()]
        .groupby(["distrito", "anyo"], as_index=False)["codigo"]
        .nunique()
        .rename(columns={"codigo": "obras_finalizadas"})
)

resumen = (
    iniciadas.merge(finalizadas, on=["distrito", "anyo"], how="left")
             .fillna({"obras_finalizadas": 0})
)
resumen["obras_finalizadas"] = resumen["obras_finalizadas"].astype(int)

resumen.to_csv("resumen_inversiones_por_inicio_std.csv", index=False, encoding="utf-8-sig")

print("OK -> resumen_inversiones_por_inicio_std.csv")

OK ✅ -> resumen_inversiones_por_inicio_std.csv / resumen_inversiones_std.xlsx

Renombrar columnas del resumen_inversiones_por_inicio_std

In [ ]:
import pandas as pd
import unicodedata
import re

# Lista estándar de distritos definidos
distritos_std = [
    "CENTRO","ARGANZUELA","RETIRO","SALAMANCA","CHAMARTIN","TETUAN","CHAMBERI",
    "FUENCARRALELPARDO","MONCLOAARAVACA","LATINA","CARABANCHEL","USERA",
    "PUENTEDEVALLECAS","MORATALAZ","CIUDADLINEAL","HORTALEZA","VILLAVERDE",
    "VILLADEVALLECAS","VICALVARO","SANBLASCANILLEJAS","BARAJAS"
]

# función para limpiar texto
def limpiar(s):
    s = str(s).upper().strip()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"[^A-Z0-9]", "", s)  # quitar espacios y símbolos
    return s

# cargar dataset
df = pd.read_csv("resumen_inversiones_por_inicio_std.csv", encoding="utf-8")

# limpiar valores de distrito
df["distrito"] = df["distrito"].map(limpiar)

# filtrar solo los distritos de la lista
df = df[df["distrito"].isin(distritos_std)].copy()

# renombrar columnas
df = df.rename(columns={
    "distrito": "Distrito",
    "anyo": "anyo",
    "obras_iniciadas": "obras_iniciadas",
    "obras_finalizadas": "obras_finalizadas"
})

df.to_csv("resumen_inversiones_por_inicio_std_clean.csv", index=False, encoding="utf-8-sig")

print(df.head())

Distritos estandarizados y depurados ✅
     Distrito  anyo  obras_iniciadas  obras_finalizadas
0  ARGANZUELA  2018                1                  1
1  ARGANZUELA  2021                4                  3
2  ARGANZUELA  2024                3                  0
3  ARGANZUELA  2025                3                  0
4  ARGANZUELA  2026                1                  0

## Unificación de dataset general_11_24_ev_renta_demog_paro_pobl_zv con el dataset resumen_inversiones_por_inicio_std_clean ##

In [ ]:
import pandas as pd

# cargar datasets
resumen = pd.read_csv("resumen_inversiones_por_inicio_std_clean.csv", encoding="utf-8")
general = pd.read_csv("general_11_24_ev_renta_demog_paro_pobl_zv.csv", encoding="utf-8")

# Aseguramos nombres sin espacios 
resumen.columns = resumen.columns.str.strip()
general.columns = general.columns.str.strip()

# LEFT JOIN para mantener todas las filas de general
df_final = pd.merge(
    general,
    resumen,
    on=["Distrito", "anyo"],
    how="left"
)

df_final.to_csv("general_11_24_ev_renta_demog_paro_pobl_zv_obras.csv", index=False, encoding="utf-8-sig")

print("Archivo generado: general_11_24_ev_renta_demog_paro_pobl_zv_obras.[csv]")
print(df_final.head())

C:\Users\andre\AppData\Local\Temp\ipykernel_12276\1679443519.py:5: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  general = pd.read_csv("general_11_24_ev_renta_demog_paro_pobl_zv.csv", encoding="utf-8")

Unificación completa ✅
Archivo generado: general_11_24_ev_renta_demog_paro_pobl_zv_obras.[csv|xlsx]
  Distrito       Barrio  anyo  Inversion  airbnb  Superficie (Ha.)  \
0   CENTRO       Cortes  2011        NaN     NaN               NaN
1   CENTRO  Embajadores  2011        NaN     NaN               NaN
2   CENTRO     Justicia  2011        NaN     NaN               NaN
3   CENTRO      Palacio  2011        NaN     NaN               NaN
4   CENTRO          Sol  2011        NaN     NaN               NaN

   Población densidad (hab./Ha.)  Tasa bruta de natalidad (‰)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

   Población en etapas educativas  \
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN

   Tasa de crecimiento demográfico (porcentaje)  ...  \
0                                           NaN  ...
1                                           NaN  ...
2                                           NaN  ...
3                                           NaN  ...
4                                           NaN  ...

   Edad media de la población_y  Población  \
0                           NaN        NaN
1                           NaN        NaN
2                           NaN        NaN
3                           NaN        NaN
4                           NaN        NaN

   Porcentaje de población de 65 y más años  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

   Porcentaje de población menor de 18 años  Tamaño medio del hogar_y  \
0                                       NaN                       NaN
1                                       NaN                       NaN
2                                       NaN                       NaN
3                                       NaN                       NaN
4                                       NaN                       NaN

   paro_registrado_anual  poblacion_anual  \
0                    NaN       14089030.0
1                    NaN       14089030.0
2                    NaN       14089030.0
3                    NaN       14089030.0
4                    NaN       14089030.0

   ha de ZONAS VERDES Y PARQUES en distrito  obras_iniciadas  \
0                                       NaN              NaN
1                                       NaN              NaN
2                                       NaN              NaN
3                                       NaN              NaN
4                                       NaN              NaN

   obras_finalizadas
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

[5 rows x 44 columns]

Corrección de Columna Población para garantizar que sea promedio mensual de población

In [ ]:
import pandas as pd
import unicodedata, re

def normaliza_distrito(s):
    if pd.isna(s): return s
    s = str(s).strip().upper()
    s = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))  # sin acentos
    return re.sub(r"\s+", "", s)  # sin espacios

# Leer el archivo con separador ;
df = pd.read_csv("poblacion_2011_2022_sin_decimales.csv", encoding="utf-8-sig", sep=";")
print("Columnas detectadas:", df.columns.tolist())

# Estandarizar columna 'Distrito'
df["Distrito"] = df["Distrito"].apply(normaliza_distrito)

# Calcular el promedio anual de la columna Total por Distrito y anyo
promedios = (
    df.groupby(["Distrito", "anyo"], as_index=False)
      .agg(promedio_anual=("Total", "mean"))
)

# Quitar decimales de la columna del promedio
promedios["promedio_anual"] = promedios["promedio_anual"].round(0).astype("Int64")

promedios.to_csv("poblacion_promedio_anual.csv", index=False, encoding="utf-8-sig", sep=";")

print("Promedio anual calculado, distritos estandarizados.")
print(promedios.head())

Columnas detectadas: ['Distrito', 'Total', 'anyo', 'Mes']
✅ Promedio anual calculado, distritos estandarizados.
     Distrito  anyo  promedio_anual
0  ARGANZUELA  2011          154417
1  ARGANZUELA  2012          154910
2  ARGANZUELA  2013          153081
3  ARGANZUELA  2014          151199
4  ARGANZUELA  2015          151180

## Unificación de datos del dataset poblacion_promedio_anual con el dataset general_11_24_ev_renta_demog_paro_pobl_zv_obras ##

In [ ]:
import pandas as pd
import io

# Lector de CSV (detecta separadores como: coma, punto y coma, tab, maneja UTF-8 con BOM
def safe_read(path):
    df = pd.read_csv(path, sep=None, engine="python", encoding="utf-8-sig", skipinitialspace=True)
    if len(df.columns) == 1 and any(ch in df.columns[0] for ch in [",",";","\t","|"]):
        text = df.columns[0] + "\n" + "\n".join(df.iloc[:,0].astype(str).tolist())
        df = pd.read_csv(io.StringIO(text), sep=",", engine="python", encoding="utf-8-sig", skipinitialspace=True)
    return df

prom    = safe_read("poblacion_promedio_anual.csv")
general = safe_read("general_11_24_ev_renta_demog_paro_pobl_zv_obras.csv")

# Quitar comillas y espacios en nombres de columnas y valores
def strip_quotes(s):
    if pd.isna(s): return s
    s = str(s).strip()
    if (len(s) >= 2) and ((s[0] == s[-1]) and s[0] in ("'", '"')):
        s = s[1:-1]
    return s.strip()

prom.columns    = [strip_quotes(c) for c in prom.columns]
general.columns = [strip_quotes(c) for c in general.columns]

for c in ["Distrito", "anyo"]:
    if c in prom.columns:
        prom[c] = prom[c].apply(strip_quotes).astype(str).str.strip().str.upper()
    if c in general.columns:
        general[c] = general[c].apply(strip_quotes).astype(str).str.strip().str.upper()

# Merge con Distrito + anyo
merged = general.merge(prom, on=["Distrito","anyo"], how="left")

output_file = "general_11_24_ev_renta_demog_paro_pobl_zv_obras_unificado.csv"
merged.to_csv(output_file, index=False, encoding="utf-8-sig")

print(f"Archivo guardado como {output_file}")

✅ Archivo guardado como general_11_24_ev_renta_demog_paro_pobl_zv_obras_unificado.csv